require('nyquist')
ad = nyquist.AudioData() 
w  = nyquist.WavDecoder("test.wav",ad)
print("channels = ", ad:channels())
print("samplerate = ", ad:sample_rate())
print("length(s) = ",ad:length_seconds())
print("frame size = ",ad:frame_size())
print("format = ", ad:format())
print("size = ", ad:size())
