DateTime.o: DateTime.cc commoncpp/DateTime.hh commoncpp/Exception.hh \
 commoncpp/Compilers.hh commoncpp/String.hh
SocketAddr.o: SocketAddr.cc commoncpp/SocketAddr.hh \
 commoncpp/Exception.hh commoncpp/Compilers.hh commoncpp/String.hh \
 commoncpp/SocketTypes.hh
SocketOp.o: SocketOp.cc commoncpp/String.hh commoncpp/Exception.hh \
 commoncpp/Compilers.hh commoncpp/SocketOp.hh commoncpp/Alloc.hh \
 commoncpp/String.hh commoncpp/SocketTypes.hh commoncpp/SocketAddr.hh
String.o: String.cc commoncpp/String.hh commoncpp/Exception.hh \
 commoncpp/Compilers.hh
Threads.o: Threads.cc commoncpp/Threads.hh commoncpp/Mutex.hh
